FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

ENV BOT_TOKEN=
ENV DUST_EMOJI_ID=
ENV COIN_EMOJI_ID=
ENV JSON_DB_FILE=
ENV DAILY_GOLD_AMOUNT=
ENV DAILY_DUST_AMOUNT=
ENV BONUS_GOLD_AMOUNT=
ENV BONUS_DUST_AMOUNT=
ENV RANDOM_CARD_COST=
ENV GOOGLE_APPLICATION_CREDENTIALS=
ENV SPREADSHEET_ID=
ENV POKEDEX_SHEET_NAME=
ENV HISTORY_SHEET_NAME=

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . /usr/src/app

CMD [ "node", "index.js" ]
