version: '3.1'

services:
  bot:
    build: .
    restart: unless-stopped
    networks:
      - net
    environment:
      BOT_TOKEN: MTAwMTA5NTM2MzAxNDQzMDgzMA.GDdogd._yyDg33J8RdMEK-o34rdDypCZ5IVY5As9e0Z5k
      DUST_EMOJI_ID: <:dust:1001431763861643334>
      COIN_EMOJI_ID: <:pokedollar:1001433965711859762>


networks:
  net:
    driver: bridge
